### ISSUE TITLE
Standalone mode does not work

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Products#4]
Exceptions on console:

```
GET http://localhost:8080/__default/D296A0EF2DB4963400000060 400 (BadRequest) at puppet.js:292
Uncaught Error: PuppetJs JSON response error. Server responded with error 400 BadRequest at puppet.js:270
```

**Comment by miyconst** [comment]
After struggling investigation I could say that this is a bug of Chrome. Google Chrome, Google Chrome Canary and Opera all behave in the same way.

Exactly the same request from Postman goes through with no errors. The request headers and details were checked with Chrome developer console and Fiddler.

Moreover, Chrome works fine, if I change main url from `http://localhost:8080/products` to `http://localhost:8080/products/all`. Exactly the same page, same files, just different url.

If I could have access to server side, maybe I could set a brake point and investigate some more.

@warpech, maybe you can find something.

**Comment by warpech** [comment]
I can't find any explanation to this. I think @chrhol needs to take a look.

**Comment by chrhol** [comment]
I get the same behaviour. For some reason the correct session is not found when retrieving the viewmodel (`GET http://localhost:8080/__default/D296A0EF2DB4963400000060`) so the server throws an IncorrectSessionException and returns a 400 error.

I will try to debug and see if I can understand why.

**Comment by chrhol** [comment]
I think I found the bug. It's in the gateway, when parsing the referer (or x-referer) header. If the value of this header is of a specific length, the gateway thinks it is a sessionid and overwrites the session with faulty values.

I'm not sure how to fix it, and I'm thinking of maybe leaving it for Alexey since he has much better grasp on how the gateway works. I will add an issue for it in Starcounter.
